spring:
  application:
    name: assessment
  datasource:
    url: jdbc:mysql://192.168.31.23:3306/assessment?characterEncoding=UTF-8&useSSL=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method